# Generated by Django 4.0.1 on 2022-01-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0003_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
