# Generated by Django 4.0.1 on 2022-01-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'School Name',
            },
        ),
        migrations.CreateModel(
            name='SClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=15)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='graph_app.school')),
            ],
            options={
                'db_table': 'Standard',
            },
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='graph_app.sclass')),
            ],
            options={
                'db_table': 'Strength',
            },
        ),
    ]
