# Generated by Django 4.0.1 on 2022-01-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0005_school_sclass_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='strength',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='graph_app.strength'),
            preserve_default=False,
        ),
    ]
